name: Deploy Wordlie

on:
  push:
    branches: [main]

env:
  COMPOSE_FILE: compose.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and deploy
        run: |
          docker compose down
          docker compose up -d --build
          
      - name: Initialize database
        run: |
          docker compose exec -T postgres bash -c \
          "until pg_isready -U postgres -d WordlieDB; do sleep 2; done"
          
          docker compose exec -T postgres bash -c \
          "sudo apt install python3-psycopg2"
    
          docker compose exec -T postgres /docker-entrypoint-initdb.d/fill_db.py